{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 23,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2020-08-06T17:28:58.447745Z",
     "start_time": "2020-08-06T17:28:57.304819Z"
    }
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 1183, in get_from_telegram_server\n",
      "    allowed_updates=allowed_upd)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 1183, in get_from_telegram_server\n",
      "    allowed_updates=allowed_upd)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 1183, in get_from_telegram_server\n",
      "    allowed_updates=allowed_upd)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 1183, in get_from_telegram_server\n",
      "    allowed_updates=allowed_upd)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[]\n"
     ]
    }
   ],
   "source": [
    "import telegram\n",
    "import time\n",
    "\n",
    "chat_token = \"1271852396:AAEltk0PRTeMy0fEQv1geYZd-DqjK-ugnZQ\"\n",
    "chat = telegram.Bot(token = chat_token)\n",
    "updates = chat.getUpdates()\n",
    "print(updates)\n",
    "for u in updates:\n",
    "    print(u.message)\n",
    "    print(u.message['chat']['id'])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2020-08-06T17:29:53.297053Z",
     "start_time": "2020-08-06T17:29:42.291494Z"
    }
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 1183, in get_from_telegram_server\n",
      "    allowed_updates=allowed_upd)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 1183, in get_from_telegram_server\n",
      "    allowed_updates=allowed_upd)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 1183, in get_from_telegram_server\n",
      "    allowed_updates=allowed_upd)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "ww\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 1183, in get_from_telegram_server\n",
      "    allowed_updates=allowed_upd)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "text private 1054497621\n",
      "text private 1054497621\n",
      "text private 1054497621\n",
      "text private 1054497621\n",
      "text private 1054497621\n",
      "text private 1054497621\n",
      "text private 1054497621\n",
      "text private 1054497621\n",
      "text private 1054497621\n",
      "text private 1054497621\n",
      "text private 1054497621\n",
      "text private 1054497621\n",
      "text private 1054497621\n",
      "text private 1054497621\n",
      "text private 1054497621\n",
      "text private 1054497621\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 1183, in get_from_telegram_server\n",
      "    allowed_updates=allowed_upd)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 1183, in get_from_telegram_server\n",
      "    allowed_updates=allowed_upd)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 1183, in get_from_telegram_server\n",
      "    allowed_updates=allowed_upd)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 1183, in get_from_telegram_server\n",
      "    allowed_updates=allowed_upd)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 1183, in get_from_telegram_server\n",
      "    allowed_updates=allowed_upd)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 1183, in get_from_telegram_server\n",
      "    allowed_updates=allowed_upd)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 1183, in get_from_telegram_server\n",
      "    allowed_updates=allowed_upd)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 1183, in get_from_telegram_server\n",
      "    allowed_updates=allowed_upd)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 1183, in get_from_telegram_server\n",
      "    allowed_updates=allowed_upd)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 1183, in get_from_telegram_server\n",
      "    allowed_updates=allowed_upd)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 1183, in get_from_telegram_server\n",
      "    allowed_updates=allowed_upd)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 1183, in get_from_telegram_server\n",
      "    allowed_updates=allowed_upd)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 1183, in get_from_telegram_server\n",
      "    allowed_updates=allowed_upd)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 1183, in get_from_telegram_server\n",
      "    allowed_updates=allowed_upd)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 1183, in get_from_telegram_server\n",
      "    allowed_updates=allowed_upd)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 1183, in get_from_telegram_server\n",
      "    allowed_updates=allowed_upd)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 1183, in get_from_telegram_server\n",
      "    allowed_updates=allowed_upd)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 1183, in get_from_telegram_server\n",
      "    allowed_updates=allowed_upd)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 1183, in get_from_telegram_server\n",
      "    allowed_updates=allowed_upd)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 1183, in get_from_telegram_server\n",
      "    allowed_updates=allowed_upd)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 1183, in get_from_telegram_server\n",
      "    allowed_updates=allowed_upd)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 1183, in get_from_telegram_server\n",
      "    allowed_updates=allowed_upd)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 1183, in get_from_telegram_server\n",
      "    allowed_updates=allowed_upd)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 1183, in get_from_telegram_server\n",
      "    allowed_updates=allowed_upd)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"/home/markcha/anaconda3/envs/py366/lib/python3.6/site-packages/telepot/api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n"
     ]
    },
    {
     "ename": "KeyboardInterrupt",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mKeyboardInterrupt\u001b[0m                         Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-24-91a5d9d88aba>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m     14\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     15\u001b[0m \u001b[0;32mwhile\u001b[0m \u001b[0;36m1\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 16\u001b[0;31m     \u001b[0mtime\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msleep\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;36m10\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;31mKeyboardInterrupt\u001b[0m: "
     ]
    }
   ],
   "source": [
    "\n",
    "import time\n",
    "import telepot\n",
    "\n",
    "def handle(msg):\n",
    "    content_type, chat_type, chat_id = telepot.glance(msg)\n",
    "    print(content_type, chat_type, chat_id)\n",
    "#     if content_type=='text':\n",
    "#         bot.sendMessage(chat_id, msg['text'])\n",
    "        \n",
    "        \n",
    "bot = telepot.Bot(\"1271852396:AAEltk0PRTeMy0fEQv1geYZd-DqjK-ugnZQ\")\n",
    "bot.message_loop(handle)\n",
    "print('ww')\n",
    "\n",
    "while 1:\n",
    "    time.sleep(10)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.6"
  },
  "varInspector": {
   "cols": {
    "lenName": "1001000000",
    "lenType": "10000000",
    "lenVar": "1000000000"
   },
   "kernels_config": {
    "python": {
     "delete_cmd_postfix": "",
     "delete_cmd_prefix": "del ",
     "library": "var_list.py",
     "varRefreshCmd": "print(var_dic_list())"
    },
    "r": {
     "delete_cmd_postfix": ") ",
     "delete_cmd_prefix": "rm(",
     "library": "var_list.r",
     "varRefreshCmd": "cat(var_dic_list()) "
    }
   },
   "types_to_exclude": [
    "module",
    "function",
    "builtin_function_or_method",
    "instance",
    "_Feature"
   ],
   "window_display": true
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
